ulan/main/urls.py
from django.urls import path
from .views import (KroyListView, KroyCreateView, KroyUpdateView, KroyDetailListView,
                    KroyDetailCreateView, KroyDetailUpdateView, create_masterdata, MasterdataListView,
                    MdataKroyDetailView, MasterdatauserListView)

from . import views


urlpatterns = [
    path("", views.index, name="home"),
    path("index", views.index),

    path('kroy/', KroyListView.as_view(), name='kroy-list'),
    path('kroy/create/', KroyCreateView.as_view(), name='kroy-create'),
    path('<int:kroy_id>/', views.KroyDetailView, name='kroy-detail-view'),
    path('kroy/update/<int:pk>/', KroyUpdateView.as_view(), name='kroy-update'),
    path('kroy-detail/', KroyDetailListView.as_view(), name='kroy-detail-list'),
    path('kroy-detail/create/', KroyDetailCreateView.as_view(), name='kroy-detail-create'),
    path('kroy-detail/update/<int:pk>/', KroyDetailUpdateView.as_view(), name='kroy-detail-update'),
    path('create_masterdata', views.create_masterdata, name='create_masterdata'),
    #path('add_masterdata', views.add_masterdata, name='add_masterdata'),
    path('masterdata', MasterdataListView.as_view(), name='masterdata_list'),
    path('masterdatauser', views.MasterdatauserListView, name='masterdatauser_list'),
    path('<int:kroy_id>/', views.MdataKroyDetailView, name='mdata-kroy-detail-view'),



    # Changed the URL path to a different name

]

ulan/ulan/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('account/', include('account.urls')),
    path('inventory/', include('inventory.urls')),
    path('warehouse/', include('warehouse.urls'))

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ulan/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('account/', include('account.urls'))
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ulan/main/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.auth import get_user_model

def get_default_user():
    return get_user_model().objects.first()

class Kroy(models.Model):
    class Meta:
            verbose_name_plural = ('Крой')
    name = models.CharField(max_length=250, verbose_name='Наименование')
    kroy_no = models.IntegerField(verbose_name='Крой номер')
    ras_tkani = models.FloatField(verbose_name='Расход ткани')
    ras_dublerin = models.FloatField(verbose_name='Расход дублерин')
    edinitsa = models.IntegerField(null=True, blank=True, verbose_name='Единица')
    description = models.TextField(null=True, blank=True, verbose_name='Примечение')
    created = models.DateTimeField(auto_now_add=True, verbose_name='Дата создание')
    is_active = models.BooleanField(default=True, verbose_name='Активен')

    def update_edinitsa(self):
        # Calculate the sum of stuk from related Kroy_detail objects
        total_stuk = self.kroy_detail_set.aggregate(total_stuk=models.Sum('stuk'))['total_stuk']

        if total_stuk is not None:
            # Add the sum to the edinitsa field
            self.edinitsa = self.edinitsa + total_stuk
            self.save()

    def __str__(self):
        return str(self.kroy_no)

class Kroy_detail(models.Model):
    class Meta:
            verbose_name_plural = ('Крой детально')
    kroy = models.ForeignKey(Kroy, on_delete=models.CASCADE, verbose_name='Крой')
    pachka = models.CharField(max_length=200, verbose_name='Пачка')
    razmer = models.CharField(max_length=200, verbose_name='Размер')
    rost = models.CharField(max_length=200, verbose_name='Рост')
    stuk = models.IntegerField(verbose_name='Штук')
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Пользователь')
    created = models.DateTimeField(auto_now_add=True, verbose_name='Created at')


    def __str__(self):
        return self.pachka

class Masterdata(models.Model):
    class Meta:
            verbose_name_plural = ('Общая таблица')
    OPTION_CHOICES = [
        ('в процессе', 'в процессе'),
        ('звершень', 'звершень'),
    ]
    status = models.CharField(max_length=50, choices=OPTION_CHOICES, default='в процессе')
    kroy_no = models.IntegerField(verbose_name='Крой номер')
    edinitsa = models.IntegerField(verbose_name='Единица')
    created = models.DateTimeField(auto_now_add=True, verbose_name='Дата')
    is_active = models.BooleanField(default=True, verbose_name='Активен')
    description = models.TextField(null=True, blank=True, verbose_name='Примечение')
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Пользователь')

    def __str__(self):
        return f"{self.status} - {self.kroy_no}"

ulan/main/forms.py
from django import forms
from .models import Kroy, Kroy_detail, Masterdata
from django.contrib.auth.models import User
from django.contrib.auth import get_user_model

class KroyForm(forms.ModelForm):
    class Meta:
        model = Kroy
        fields = ['kroy_no', 'name', 'ras_tkani', 'ras_dublerin', 'edinitsa', 'description']

class KroyDetailForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(KroyDetailForm, self).__init__(*args, **kwargs)
        self.fields['user'].queryset = get_user_model().objects.all()

    class Meta:
        model = Kroy_detail
        fields = ['kroy', 'pachka', 'razmer', 'rost', 'stuk', 'user']  # You can specify specific fields if needed

    user = forms.ModelChoiceField(
        queryset=get_user_model().objects.all(),
        widget=forms.HiddenInput(),
        initial=get_user_model().objects.get(username='admin')
    )

class MasterdataSearchForm(forms.Form):
    start_date = forms.DateField(label='Дата начала', required=False)
    end_date = forms.DateField(label='Дата окончания', required=False)
    uchastok_search = forms.CharField(label='Искать по участке', required=False)
    kroy_no_search = forms.CharField(label='Искать по крой но:', required=False)

class MasterdataForm(forms.ModelForm):
    class Meta:
        model = Masterdata
        fields = ['user']  # Add other fields as needed

ulan/main/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import ListView, CreateView, UpdateView
from .models import Kroy, Kroy_detail #Uchastok
from .forms import KroyForm, KroyDetailForm, Masterdata, MasterdataSearchForm, MasterdataForm
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.contrib.auth.models import User
from django.urls import reverse_lazy

from django.contrib import messages


def index(request):
    if not request.user.is_authenticated:
        return redirect("login")
    return render(request, "main/index.html")

def create_masterdata(request):
    if not request.user.is_authenticated:
        return redirect("login")

    if request.method == 'POST':
        kroy_no = request.POST.get('kroy_no')
        edinitsa = request.POST.get('edinitsa')
        username = request.POST.get('user')  # Get the username

        try:
            edinitsa = int(edinitsa)
        except ValueError:
            edinitsa = 0  # Default value if parsing fails

        # Create a new Masterdata object and save it to the database
        #uchastok = get_object_or_404(Uchastok, pk=uchastok)

        # Get the User instance based on the username
        user = get_object_or_404(User, username=username)

        masterdata = Masterdata(
            kroy_no=kroy_no,
            #uchastok=uchastok,
            edinitsa=edinitsa,
            user=user,  # Assign the User instance
            # Add other fields here as needed
        )
        masterdata.save()

        kroy_record = get_object_or_404(Kroy, kroy_no=kroy_no)
        kroy_record.edinitsa = int(kroy_record.edinitsa or 0) - edinitsa
        kroy_record.save()

        return redirect('masterdata_list')

    return render(request, 'main/kroy/kroy_masterdata.html')

class MasterdataListView(ListView):
    model = Masterdata
    template_name = 'main/mdata/masterdata_list.html'
    context_object_name = 'masterdata_list'

    def get_queryset(self):
        form = MasterdataSearchForm(self.request.GET)
        queryset = Masterdata.objects.filter(is_active=True)

        if form.is_valid():
            start_date = form.cleaned_data.get('start_date')
            end_date = form.cleaned_data.get('end_date')
            #uchastok_search = form.cleaned_data.get('uchastok_search')
            kroy_no_search = form.cleaned_data.get('kroy_no_search')

            filter_conditions = Q()

            if start_date:
                filter_conditions &= Q(created__gte=start_date)
            if end_date:
                filter_conditions &= Q(created__lte=end_date)
            #if uchastok_search:
                #queryset = queryset.filter(Q(uchastok__name__icontains=uchastok_search))
            if kroy_no_search:
                filter_conditions &= Q(kroy_no__icontains=kroy_no_search)

                # Apply the combined filters
            queryset = queryset.filter(filter_conditions)

        queryset = queryset.order_by('-created')
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['search_form'] = MasterdataSearchForm(self.request.GET)
        context['additional_variable'] = 'Some additional value'

        return context

def MdataKroyDetailView(request, kroy_id):
        kroy_instance = get_object_or_404(Masterdata, pk=kroy_id)
        kroy_details = Kroy_detail.objects.filter(kroy=kroy_instance)  # Retrieve related Kroy_detail records

        context = {
            'kroy_instance': kroy_instance,
            'kroy_details': kroy_details,  # Pass the related records to the template
        }
        return render(request, 'main/dmata/dmata_kroy_detail_view.html', context)

class KroyListView(ListView):
    model = Kroy
    template_name = 'main/kroy/kroy_list.html'

    def get_queryset(self):
        # Filter the Kroy objects where is_active is True
        return Kroy.objects.filter(is_active=True)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        #context['uchastok'] = Uchastok.objects.all()
        context['user'] = User.objects.all()

        return context

class KroyCreateView(CreateView):
    model = Kroy
    form_class = KroyForm
    template_name = 'main/kroy/kroy_form.html'
    success_url = reverse_lazy ('kroy-create')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['kroy_list'] = Kroy.objects.all().order_by('-created')[
                                      :10]  # Add this line to pass the data to the template
        return context
def KroyDetailView(request, kroy_id):
    kroydetil_instance = Kroy_detail.objects.filter(user=request.user).first()

    if request.method == 'POST':
        form = KroyDetailForm(request.POST, instance=kroydetil_instance)
        if form.is_valid():
            form.save()
    else:
        form = KroyDetailForm(instance=kroydetil_instance)

    kroy_instance = get_object_or_404(Kroy, pk=kroy_id)
    kroy_details = Kroy_detail.objects.filter(kroy=kroy_instance)

    context = {
        'form': form,
        'kroy_instance': kroy_instance,
        'kroy_details': kroy_details,
    }
    return render(request, 'main/kroy/kroy_detail_view.html', context)

class KroyUpdateView(UpdateView):
    model = Kroy
    form_class = KroyForm
    template_name = 'main/kroy/kroy_form.html'
    success_url = '/kroy/'

class KroyDetailListView(ListView):
    model = Kroy_detail
    template_name = 'main/kroy/kroy_detail_list.html'

class KroyDetailCreateView(CreateView):
    model = Kroy_detail
    form_class = KroyDetailForm
    template_name = 'main/kroy/kroy_detail_form.html'
    success_url = reverse_lazy('kroy-detail-create')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['kroy_detail_list'] = Kroy_detail.objects.all().order_by('-created')[:10]  # Add this line to pass the data to the template
        return context

class KroyDetailUpdateView(UpdateView):
    model = Kroy_detail
    form_class = KroyDetailForm
    template_name = 'main/kroy/kroy_detail_form.html'
    success_url = '/kroy-detail/'

@login_required
def MasterdatauserListView(request):

    if request.method == 'POST':
        kroy_no = request.POST.get('kroy_no')
        edinitsa = request.POST.get('edinitsa')

        # No need to get the username separately; use request.user directly
        user = request.user

        masterdata = Masterdata(
            kroy_no=kroy_no,
            edinitsa=edinitsa,
            user=user,
        )
        masterdata.save()

    context = {
        'masterdata_list': Masterdata.objects.filter(user=request.user),
        'kroy_detail_list': Kroy_detail.objects.filter(user=request.user),
        'user': request.user,
        'kroy_list': Kroy.objects.all(),
    }

    return render(request, 'main/masterdatauser_list.html', context)

ulan/main/templates/main/mdata/_masterdata_list.html
<form method="get">
    <div class="row mt-2">
        <div class="col">
            <label for="id_start_date">Дата начала:</label>
            <input type="text" class="form-control form-control-sm"
                   id="id_start_date"
                   name="{{ search_form.start_date.name }}"
                   value="">
        </div>
        <div class="col">
            <label for="id_end_date">Дата окончания:</label>
            <input type="text" class="form-control form-control-sm"
                   id="id_end_date"
                   name="{{ search_form.end_date.name }}"
                   value="">
        </div>
        <div class="col">
            <label for="id_uchastok_search">Участка:</label>
            <input type="text" class="form-control form-control-sm"
                   id="id_uchastok_search"
                   name="{{ search_form.uchastok_search.name }}"
                   value="">
        </div>
        <div class="col">
            <label for="id_kroy_no_search">Крой №:</label>
            <input type="text" class="form-control form-control-sm"
                   id="id_kroy_no_search"
                   name="{{ search_form.kroy_no_search.name }}"
                   value="">
        </div>
        <div class="col">
            <label for="button"></label>
            <button type="submit" class="btn btn-sm btn-secondary mt-4" id="button">Показать</button>
        </div>
    </div>
</form>

<table class="table caption-top">
        <caption>Рабочий процесс</caption>
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Крой номер</th>
                <th scope="col">Участок</th>
                <th scope="col">Единица</th>
                <th scope="col">Дата</th>
                <th scope="col">Статус</th>
                <th scope="col">Примечение</th>

            </tr>
        </thead>
        <tbody>
            {% for masterdata in masterdata_list %}
            <tr>
                <th scope="row">{{ forloop.counter }}</th>
                <td>{{ masterdata.kroy_no }}</td>
                <td></td>
                <td>{{ masterdata.edinitsa }}</td>
                <td>{{ masterdata.created|date:"d.m.Y H:i" }}</td>
                <td><b style="color: green;">{{ masterdata.status }}-({{ masterdata.user }})</b></td>
                <td>{{ masterdata.description }}</td>

            </tr>
            {% empty %}
            <tr>
                <td colspan="6">No records found.</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>

ulan/main/templates/main/mdata/masterdata_list.html
{% extends "base.html" %}
{% load static %}

{% block css_files %}
<link rel="stylesheet" href="{% static 'main/css/style.css' %}">
{% endblock %}

{% block title %} Home {% endblock %}

{% block content %}
<!-- kroy_masterdata.htm -->

<div class="container">
    {% include 'main/mdata/_masterdata_list.html' %}

</div>

{% endblock %}

{% block js_files %}
<script src="{% static 'main/js/script.js' %}"></script>

{% endblock %}

ulan/main/templates/main/mdata/mdata_kroy_detail_view.html
{% extends "base.html" %}
{% load static %}

{% block css_files %}
<link rel="stylesheet" href="{% static 'main/css/style.css' %}">
{% endblock %}

{% block title %} {% if form.instance.pk %}Изменить крой{% else %}Создать Кроя{% endif %} {% endblock %}

{% block content %}
<div class="container">

<h4> Крой № {{ kroy_instance.kroy_no }} -- {{ kroy_instance.name }}</h4>
<strong> Дата создания:</strong> {{ kroy_instance.created }}, <strong>Расход ткани:</strong> {{ kroy_instance.ras_tkani }},
    <strong>Расход дублерин:</strong> {{ kroy_instance.ras_dublerin }},
    <strong>Единица:</strong> {{ kroy_instance.edinitsa }}</p>

        <table class="table caption-top w-auto h-auto">
  <caption> </caption>
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Пачка</th>
      <th scope="col">Размер</th>
      <th scope="col">Рост</th>
      <th scope="col">Штук</th>
    </tr>
  </thead>

     <tbody>
     <tr class="h-auto">
     {% for detail in kroy_details %}
  <th scope="row"></th>

      <td>{{ detail.pachka }}</td>
      <td>{{ detail.razmer }}</td>
      <td>{{ detail.rost }}</td>
      <td>{{ detail.stuk }}</td>
    </tr>
     {% empty %}
            <li>Нет доступных позиций.</li>
        {% endfor %}
  </tbody>
</table>
<p><strong>Примечение:</strong> {{ kroy_instance.description }}</p>
    <a href="{% url 'kroy-list' %}">Вернуться к списку кроя</a>
</div>
{% endblock %}

{% block js_files %}
<script src="{% static 'main/js/script.js' %}"></script>

{% endblock %}